default:
  image: python:3
  
variables:
  WHEEL_ARTIFACT: "birthdav-${CI_COMMIT_TAG}-py3-none-any.whl"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/birthdav/${CI_COMMIT_TAG}"

stages:
  - test
  - package
  - upload
  - release

test:
  stage: test
  script:
    - pip install coverage .
    - PYTHONPATH=src coverage run --source src -m unittest discover -s tests
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml

package:
  stage: package
  script:
    - pip install build
    - python -m build .
  artifacts:
    paths:
      - "dist/*.whl"
  rules:
    - if: $CI_COMMIT_TAG

upload:
  stage: upload
  image: curlimages/curl:latest
  script:
    - "curl -H \"JOB-TOKEN: ${CI_JOB_TOKEN}\" --upload-file dist/*.whl ${PACKAGE_REGISTRY_URL}/${WHEEL_ARTIFACT}"
  rules:
    - if: $CI_COMMIT_TAG

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - "true"
  release:
    name: "birthdav-${CI_COMMIT_TAG}"
    tag_name: $CI_COMMIT_TAG
    description: "BirthDAV ${CI_COMMIT_TAG}"
    assets:
      links:
        - name: ${WHEEL_ARTIFACT}
          url: "${PACKAGE_REGISTRY_URL}/${WHEEL_ARTIFACT}"
  rules:
    - if: $CI_COMMIT_TAG
